UPDATE OURWAY_SYS_LAYOUT_COMPONENT SET COLUMN_DISABLE='pageType==1||pageType==2||pageType==4' WHERE comp_id='addBtn';
UPDATE OURWAY_SYS_LAYOUT_COMPONENT SET COLUMN_DISABLE='pageType==1||pageType==3' WHERE comp_id='saveBtn';
UPDATE OURWAY_SYS_LAYOUT_COMPONENT SET COLUMN_DISABLE='pageType==3||pageType==4' WHERE comp_id='removeBtn';
UPDATE OURWAY_SYS_LAYOUT_COMPONENT SET COLUMN_DISABLE='pageType==2||pageType==4' WHERE comp_id='updateBtn';
UPDATE OURWAY_SYS_LAYOUT_COMPONENT SET COLUMN_DISABLE='pageType==3' WHERE comp_id='invokeBtn';
UPDATE OURWAY_SYS_LAYOUT_COMPONENT SET COLUMN_DISABLE='pageType==3' WHERE comp_id='revokeBtn';